### PR TITLE
Add code smells and heuristics notes from...

### PR DESCRIPTION
**Pull request by IanGrainger**
janaipakos/Clean-Code-Smells-and-Heuristics

### CODE REVIEW

**Comment by JuanCrg90** [comment]
looks awesome 😄 could you send this (2b2ffef1a975fc6a32a7a73ad2a9def30250c7a8) in two separate commits?

One commit for the duplicate line, and one commit for the format update 😄 

Thanks in advance.

**Comment by IanGrainger** [comment]
> One commit for the duplicate line, and one commit for the format update 😄

Reverted the double change and made them separately.

**Comment by JuanCrg90** [comment]
Awesome, Thanks

**Comment by ghost** [comment]
Great! Glad I could help.

**Pull request merged**
